FROM python:3.8

RUN python -m pip install --upgrade pip
RUN pip install pyserial

RUN apt-get update
RUN apt-get install git
RUN apt-get install make

ADD ./arduino-esp32 /arduino-esp32
ADD ./makeEspArduino /makeEspArduino

COPY ./src/app.cpp /src/app.cpp
COPY ./esp-build-extract.sh /esp-build-extract.sh

WORKDIR /makeEspArduino
COPY ./libraries ./libraries
CMD . /esp-build-extract.sh